### ISSUE TITLE
Let composer do autoload

### ISSUE THREAD

**Issue by Doka-NT** [Bashka/taskbot#1]
If you already use composer, I think it would be better to use autoloader it provides. 

It will be such as

``` json
  "autoload": {
    "psr-4": {
      "": "."
    }
  }
```

or better way is to move your source files to _src_ directory and use namespace

``` json
  "autoload": {
    "psr-4": {
      "bashka\\taskbot\\": "src"
    }
  }
```

**Comment by Bashka** [comment]
[Done](https://github.com/Bashka/taskbot/releases/tag/v0.10)
